### ISSUE TITLE
Add to Dashboard button drodown just shows loading

### ISSUE THREAD

**Issue by pbr0ck3r** [billmurrin/graylog-plugin-quickvaluesplus-widget#45]
I get the following error in the console when I click the `Quick Values Plus` link to show the Quick Values Plus Graphs on a stream. 

```
TypeError: g.addOnWritableDashboardsChangedCallback is not a function[Learn More]
AddToDashboardMenuRev.jsx:53:4
```

When I go to click the `Add to Dashboard` button, I just get a dropdown that says `Loading`

I just upgraded from version 3.0.3 to 3.1.0... also am running the latest GL 2.4.4

**Comment by pbr0ck3r** [comment]
You can disregard this issue @billmurrin... just re-read the description of QVP-3.1.0 where you stated it only works with GL 2.3 for right now. Looking forward to the compatibility with 2.4. As always willing to help debug and help with PR's.
